# Packager. Runs on refs/tags/*
trigger:
  branches:
    include:
      - refs/tags/*
pr: none
jobs:
  - template: templates/package.yml
    parameters:
      pool:
        vmImage: 'macOS-12'
      name: 'osx_package'
  - template: templates/package.yml
    parameters:
      pool:
        vmImage: 'windows-2022'
      name: 'windows_package'
      buildScript: 'npx electron-builder build -w --ia32 --x64 --publish always'
  - template: templates/package.yml
    parameters:
      pool:
        vmImage: 'ubuntu-22.04'
      name: 'linux_package'
