# Packager. Runs on refs/tags/*
trigger:
  branches:
    include:
      - refs/tags/*
pr: none
jobs:
  - template: templates/package.yml
    parameters:
      pool:
        vmImage: 'macOS-latest'
      name: 'macos_package'
  - template: templates/package.yml
    parameters:
      pool:
        vmImage: 'windows-latest'
      name: 'windows_package'
  - template: templates/package.yml
    parameters:
      pool:
        vmImage: 'ubuntu-latest'
      name: 'linux_package'
