name: Update language resources

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: node ./ci-jobs/crowdin-update-resources.js
      env:
        CROWDIN_PROJECT_ID: appium-desktop
        CROWDIN_PROJECT_KEY: ${{ secrets.CROWDIN_PROJECT_KEY }}
      name: Crowdin Update
