# Updates Crowdin with any changes in the English translation file (/assets/locales/en/translation.json)

name: Update Crowdin English Resources

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js LTS
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Crowdin Update
      run: npm run crowdin-update
      env:
        CROWDIN_PROJECT_ID: appium-desktop
        CROWDIN_PROJECT_KEY: ${{ secrets.CROWDIN_PROJECT_KEY }}
      
