name: PR Validation

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        image: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v3
    - name: Prepare Xvfb if needed
      if: ${{ matrix.image == 'ubuntu-latest' }}
      run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
